//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceItem
    {
        public int AdvanceID { get; set; }
        public int ActivityID { get; set; }
        public string AdvanceName { get; set; }
        public int RequestAmount { get; set; }
        public int ReceiveAmount { get; set; }
        public string AdvanceRemarks { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool SelectedRow { get; set; }
        public string Status { get; set; }
    }
}
