//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpenseID { get; set; }
        public string ExpenseType { get; set; }
        public int ExpenseAmount { get; set; }
        public string ExpenseDescription { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public bool SelectedRow { get; set; }
        public string Status { get; set; }
        public int UserID { get; set; }
    }
}
