//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST
    {
        public int GSTId { get; set; }
        public int OrgID { get; set; }
        public int GSTReceived { get; set; }
        public int GSTInput { get; set; }
        public int PreviousGSTDues { get; set; }
        public int Penalty { get; set; }
        public int GSTPayable { get; set; }
        public System.DateTime TaxMonth { get; set; }
    }
}
