//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewViewPaymentGiven
    {
        public Nullable<int> ProjectId { get; set; }
        public int InvoiceId { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    }
}
