//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class oldViewActivityDashboard
    {
        public Nullable<int> ActivitiesCount { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> Spent { get; set; }
        public Nullable<int> Received { get; set; }
        public Nullable<int> Advance { get; set; }
    }
}
