//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int OrganizationID { get; set; }
        public string OrganizationNumber { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> Employee { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public string Status { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
