//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGiven
    {
        public int ID { get; set; }
        public int PInvoiceId { get; set; }
        public int OrgId { get; set; }
        public int ProjectId { get; set; }
        public double Paid { get; set; }
        public double TaxPaid { get; set; }
        public double TDSPayable { get; set; }
        public string TDSStatus { get; set; }
        public System.DateTime PaymentDate { get; set; }
    }
}
