//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string ProjectNumber { get; set; }
        public string ClientName { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ProjectValue { get; set; }
        public string ProjectDescription { get; set; }
        public System.DateTime ProjectCreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public int OrgID { get; set; }
    }
}
