//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStatu
    {
        public int ID { get; set; }
        public Nullable<int> WorkCompletion { get; set; }
        public string Remarks { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int ProjectID { get; set; }
        public string Status { get; set; }
    }
}
