//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportedIssue
    {
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public decimal Lattitude { get; set; }
        public decimal Longitude { get; set; }
        public int Type { get; set; }
        public int severity { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime ModifiedAt { get; set; }
    }
}
