//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTransactionDailyAccount
    {
        public int OrgID { get; set; }
        public int AccID { get; set; }
        public Nullable<System.DateTime> AgrregateDate { get; set; }
        public Nullable<int> Deposit { get; set; }
        public Nullable<int> Withdraw { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> AccountBalance { get; set; }
        public Nullable<System.TimeSpan> tTime { get; set; }
    }
}
