//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProjectExpense
    {
        public int ProjectID { get; set; }
        public Nullable<int> Expense { get; set; }
        public Nullable<int> ReceiveAmount { get; set; }
        public Nullable<System.DateTime> exdate { get; set; }
    }
}
