//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPurchaseInvoice
    {
        public int OrgId { get; set; }
        public int ProjectId { get; set; }
        public string VendorName { get; set; }
        public int InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public double ServiceCost { get; set; }
        public double CGST { get; set; }
        public double SGST { get; set; }
        public double IGST { get; set; }
        public double TDS { get; set; }
        public double Payable { get; set; }
        public int PaidAmount { get; set; }
        public System.DateTime PaidDate { get; set; }
        public string ProjectName { get; set; }
        public string ProjectNumber { get; set; }
        public string ClientName { get; set; }
        public int CreatedBy { get; set; }
    }
}
