//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewExpenseItemDailyStatu
    {
        public int OrgID { get; set; }
        public int ProjectID { get; set; }
        public int ActivityID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public Nullable<System.DateTime> ExpensesDate { get; set; }
        public string ActivityStatus { get; set; }
        public Nullable<int> Expense { get; set; }
        public Nullable<int> Received { get; set; }
    }
}
