//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAdvanceStatu
    {
        public int ActivityNumber { get; set; }
        public string AdvanceName { get; set; }
        public string AdvanceStatus { get; set; }
        public Nullable<System.DateTime> AdvanceModifiedDate { get; set; }
    }
}
