//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTransaction
    {
        public System.DateTime EntryDate { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransID { get; set; }
        public string TransName { get; set; }
        public int AccID { get; set; }
        public int Deposit { get; set; }
        public int Withdraw { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> AccountBalance { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int ActivityID { get; set; }
        public int TransactionID { get; set; }
        public string TransactionRemarks { get; set; }
        public int OrgID { get; set; }
        public string TransType { get; set; }
        public string AccountName { get; set; }
    }
}
