//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewActivitySummary
    {
        public long RowID { get; set; }
        public int OrgID { get; set; }
        public string ActivityStatus { get; set; }
        public Nullable<int> Expense { get; set; }
        public Nullable<int> Received { get; set; }
    }
}
