//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XPenEntities : DbContext
    {
        public XPenEntities()
            : base("name=XPenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<AdvanceItem> AdvanceItems { get; set; }
        public virtual DbSet<CatchUpUser> CatchUpUsers { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<GST> GSTs { get; set; }
        public virtual DbSet<NewViewActivity> NewViewActivities { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual DbSet<ReportedIssue> ReportedIssues { get; set; }
        public virtual DbSet<TD> TDS { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserImage> UserImages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ExpenseItem> ExpenseItems { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<SalesInvoice> SalesInvoices { get; set; }
    }
}
